### ISSUE TITLE
4.4.x compatibility

### ISSUE THREAD

**Issue by SystemsModelling** [jonarnoldmusic/musicaFicta#2]
I added the title and category so it does not appear with no name.
[musicaFicta_2.qml.txt](https://github.com/user-attachments/files/17534658/musicaFicta_2.qml.txt)

I looked the doc on how to contribute to open source but it looks like a lot of setup and overhead work just to upload another file. I hope this helps.
https://opensource.guide/how-to-contribute

**Comment by jonarnoldmusic** [comment]
Thanks, I've updated the main branch now.
